/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcus
 */
public class FeldPanel extends javax.swing.JPanel {

    Color background;
    String backGround;
    boolean empty = true;
    String typ;
    String farbe;
    int x;
    int y;
    Random r;
    String path2 = "C:\\Users\\Marcus\\Documents\\GitHub\\Arimaa\\src\\backgrounds\\";
    
    /**
     * Creates new form FeldPanel
     */
    public FeldPanel() {
        initComponents();
        r = new Random();
    }
    
    public void setBackground(String s){
        backGround = s;
    }
 
    public void paintBackground(Graphics g){
        if (backGround != null){
            try {
                BufferedImage background = javax.imageio.ImageIO.read(new File(backGround));
                g.drawImage(background, 0, 0, this);
            } catch (IOException e) {
                System.out.println("Background " + backGround + "nicht gefunden!");
            }
        }
    }
    
    protected void paintComponent(Graphics g){
        super.paintComponent(g);
        paintBackground(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
