/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Random;

/**
 *
 * @author Marcus
 */
public class FeldPanel extends javax.swing.JPanel {

    Color background;
    String backGround;
    boolean empty = true;
    String typ;
    String farbe;
    int x;
    int y;
    Random r;
    String path2 = "C:\\Users\\Marcus\\Documents\\NetBeansProjects\\Arimaa\\src\\design_package\\backgrounds\\";
    
    /**
     * Creates new form FeldPanel
     */
    public FeldPanel() {
        initComponents();
        r = new Random();
    }
    
    public void setBackground(String s){
        if (r != null) {
            Image background = Toolkit.getDefaultToolkit().createImage(path2+"background"+r.nextInt(12));
            //g.drawImage(background, 0, 0, this);
        }
    }
    
    protected void paintComponent(Graphics g){
        super.paintComponent(g);
        //paintBackground(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
